export const DOCUMENT = [
    { categoryId: 1, author: "Vinh.T.P", time: "2025", conference: "ISDS 2025", keyword: "2025,keyword,AI", name: "Instruction to Programming A", image: "", href: "" },
    { categoryId: 1, author: "Vinh.T.P", time: "2025", conference: "ISDS 2025", keyword: "2025,keyword,AI", name: "Data structure", image: "", href: "" },
    { categoryId: 1, author: "Vinh.T.P", time: "2025", conference: "ISDS 2025", keyword: "2025,keyword,AI", name: "Algorithms Analysis and Design", image: "", href: "" },
    { categoryId: 1, author: "Vinh.T.P", time: "2025", conference: "ISDS 2025", keyword: "2025,keyword,AI", name: "Introduction to simulation platform", image: "", href: "" },
    { categoryId: 1, author: "Vinh.T.P", time: "2025", conference: "ISDS 2025", keyword: "2025,keyword,AI", name: "Introduction to Software Engineering", image: "", href: "" },
    { categoryId: 1, author: "Vinh.T.P", time: "2025", conference: "ISDS 2025", keyword: "2025,keyword,AI", name: "Open Source Software Development", image: "", href: "" },
    { categoryId: 1, author: "Vinh.T.P", time: "2025", conference: "ISDS 2025", keyword: "2025,keyword,AI", name: "Software Constructions", image: "", href: "" },
    { categoryId: 1, author: "Vinh.T.P", time: "2025", conference: "ISDS 2025", keyword: "2025,keyword,AI", name: "Software Requirements Engineering", image: "", href: "" },
    { categoryId: 1, author: "Vinh.T.P", time: "2025", conference: "ISDS 2025", keyword: "2025,keyword,AI", name: "Software Architecture and Design", image: "", href: "" },
    { categoryId: 1, author: "Vinh.T.P", time: "2025", conference: "ISDS 2025", keyword: "2025,keyword,AI", name: "Software Quality Assurance and Testing", image: "", href: "" },
    { categoryId: 1, author: "Vinh.T.P", time: "2025", conference: "ISDS 2025", keyword: "2025,keyword,AI", name: "Software Maintenance", image: "", href: "" },
    { categoryId: 1, author: "Vinh.T.P", time: "2025", conference: "ISDS 2025", keyword: "2025,keyword,AI", name: "Software Project Management", image: "", href: "" },
    { categoryId: 1, author: "Vinh.T.P", time: "2025", conference: "ISDS 2025", keyword: "2025,keyword,AI", name: "Data mining", image: "", href: "" },
    { categoryId: 3, author: "Vinh.T.P", time: "2025", conference: "ISDS 2025", keyword: "2025,keyword,AI", name: "Artificial Intelligence", image: "", href: "" },
    { categoryId: 2, author: "Vinh.T.P", time: "2025", conference: "ISDS 2025", keyword: "2025,keyword,AI", name: "Research methods", image: "", href: "" },
    { categoryId: 2, author: "Vinh.T.P", time: "2025", conference: "ISDS 2025", keyword: "2025,keyword,AI", name: "Advanced database", image: "", href: "" },
]
